In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [4]:
#to rename the columns
df.rename(columns = {
    'test_score(out of 10)':'test_score',
    'interview_score(out of 10)':'interview_score',
    'salary($)':'salary'
},inplace=True)

In [5]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [6]:
#to handle NaN value in column of test score
import math
median_test_score=math.floor(df.test_score.mean())
median_test_score

7

In [7]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [8]:
df.experience=df.experience.fillna('zero')
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [9]:
len(df['experience'])


8

In [10]:
for i in range(0,len(df['experience'])):
#     print(df['experience'][i])
     print(df.experience[i])
    

zero
zero
five
two
seven
three
ten
eleven


In [11]:
from word2number import w2n
df.experience=df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [12]:
# from word2number import w2n

# # converting 'one':1

# for i in range(0,len(df['experience'])):
#     df['experience'][i]=w2n.word_to_num(df['experience'][i])


In [13]:
df=df.fillna({
    'test_score':median_test_score
})

In [14]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [15]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [16]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [17]:
reg.intercept_

14992.65144669314

In [18]:
reg.predict([[2,9,6]])

C:\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [19]:
reg.predict([[12,10,10]])

C:\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])